name: _job_upload

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  upload:
    name: Upload ${{ inputs.name }}
    strategy:
      matrix:
        include:
          - file: ${{ inputs.name }}.tar.gz
          - file: ${{ inputs.name }}.tar.zst
          - file: ${{ inputs.name }}.sha512sum
    runs-on: ubuntu-latest
    steps:
      - name: Ensure release exists
        run: |
          gh release view "${{ inputs.version }}" >/dev/null 2>&1 || \
          gh release create "${{ inputs.version }}" --latest --title "${{ inputs.version }}" --notes ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download ${{ matrix.file }} artifact
        uses: actions/download-artifact@v6
        with:
          name: ${{ matrix.file }}

      - name: Upload ${{ matrix.file }} to release
        run: >
          gh release upload
          "${{ inputs.version }}"
          "${{ matrix.file }}"
          --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
